version: No.{build}
skip_tags: false
branches:
  only:
    - newnt
clone_depth: 50
platform: x86
install:
  - cmd: git submodule update --init
  - ps: Remove-Item -Recurse bundle-xmake-src
  - ps: Invoke-WebRequest "https://github.com/tboox/xmake/releases/download/v2.1.3/xmake-v2.1.3.exe" -OutFile "xmake-installer.exe"
  - cmd: xmake-installer.exe /S /D=C:\xmake
  - cmd: PATH=%PATH%;C:\xmake
  - ps: Remove-Item xmake-installer.exe
build_script:
  - cmd: cd capture_output
  - cmd: xmake -v
  - cmd: cd build
  - ps: Copy-Item winpty.dll capture_output.dll winpty-agent.exe ..\..
  - cmd: cd ..\..
  - ps: Remove-Item -Recurse capture_output
artifacts:
  - path: .
    name: ts-xmake-gui-newnt
deploy:
  - provider: GitHub
    artifact: .
    draft: true
    description: 'temp'
    on:
      appveyor_repo_tag: true
    auth_token:
      secure: i6fhYJ/A8hJC3+zb+jwRNljh5pGKxhC03D5Gla6EowVBLaFolxA8X3ZeXE0aE0pZ
