version: No.{build}
skip_tags: false
branches:
  only:
    - newnt
clone_depth: 50
platform: x86
install:
  - cmd: git submodule update --init
  - ps: Invoke-WebRequest "https://github.com/tboox/xmake/releases/download/v2.1.3/xmake-v2.1.3.exe" -OutFile "xmake-installer.exe"
  - cmd: xmake-installer.exe /S /D=C:\xmake
  - cmd: PATH=%PATH%;C:\xmake
  - ps: Remove-Item xmake-installer.exe
  - cmd: pip install pyinstaller
build_script:
  - cmd: cd capture_output
  - cmd: xmake -v
  - cmd: cd build
  - ps: Copy-Item winpty.dll,capture_output.dll,winpty-agent.exe ..\..
  - cmd: cd ..\..
  - ps: Remove-Item -Recurse -Force capture_output
after_build:
  - ps: Remove-Item -Recurse -Force .git
  - cmd: cd ..
  - cmd: mkdir temp
  - ps: Move-Item ts-xmake-gui temp
  - ps: Move-Item temp ts-xmake-gui
  - cmd: cd ts-xmake-gui
  - ps: Copy-Item -Recurse ts-xmake-gui ts-xmake-gui-installer
  - cmd: cd ts-xmake-gui-installer
  - cmd: pyinstaller -w ts-xmake-gui.py
  - ps: Copy-Item -Force winpty.dll,capture_output.dll,winpty-agent.exe dist\ts-xmake-gui
  - cmd: cd ..
  - ps: Move-Item ts-xmake-gui-installer\dist\ts-xmake-gui ts-xmake-gui-newnt-bundle
artifacts:
  - path: ts-xmake-gui
    name: ts-xmake-gui-newnt
  - path: ts-xmake-gui-newnt-bundle
    name: ts-xmake-gui-newnt-bundle
deploy:
  - provider: GitHub
    artifact: ts-xmake-gui-newnt,ts-xmake-gui-newnt-bundle
    draft: true
    description: 'temp'
    on:
      appveyor_repo_tag: true
    auth_token:
      secure: i6fhYJ/A8hJC3+zb+jwRNljh5pGKxhC03D5Gla6EowVBLaFolxA8X3ZeXE0aE0pZ
