version: No.{build}
skip_tags: false
skip_non_tags: true
image: Visual Studio 2013
clone_depth: 50
platform: x86
install:
  - C:\Python34\Scripts\pip install pyinstaller
build_script:
  - C:\Python34\Scripts\pyinstaller -F ts-xmake-gui.py
  - ps: Move-Item dist\ts-xmake-gui.exe dist\ts-xmake-gui3.exe
artifacts:
  - path: dist\ts-xmake-gui3.exe
    name: ts-xmake-gui
deploy:
  - provider: GitHub
    artifact: dist\ts-xmake-gui3.exe
    draft: true
    description: 'temp'
    on:
      appveyor_repo_tag: true
    auth_token:
      secure: i6fhYJ/A8hJC3+zb+jwRNljh5pGKxhC03D5Gla6EowVBLaFolxA8X3ZeXE0aE0pZ
