version: No.{build}
skip_tags: false
branches:
  only:
    - newnt-single
clone_depth: 1
platform: x86
install:
  - cmd: pip install pyinstaller
before_build:
  - cmd: git submodule update --init
build_script:
  - cmd: cd winpty
  - cmd: vcbuild.bat --msvc-platform Win32
  - cmd: cd ..
  - ps: Copy-Item winpty\src\Release\Win32\winpty-agent.exe,winpty\src\Release\Win32\winpty.dll .
after_build:
  - cmd: pyinstaller -F -w --add-binary winpty-agent.exe;. ts-xmake-gui.py
artifacts:
  - path: dist\ts-xmake-gui.exe
    name: ts-xmake-gui-newnt
deploy:
  - provider: GitHub
    artifact: ts-xmake-gui-newnt
    draft: true
    description: 'temp'
    on:
      appveyor_repo_tag: true
    auth_token:
      secure: i6fhYJ/A8hJC3+zb+jwRNljh5pGKxhC03D5Gla6EowVBLaFolxA8X3ZeXE0aE0pZ
