version: No.{build}
skip_tags: false
branches:
  only:
    - newnt
clone_depth: 1
platform: x86
install:
  - cmd: git submodule update --init
  - ps: Invoke-Expression (Invoke-Webrequest 'https://raw.githubusercontent.com/tboox/xmake/master/scripts/get.ps1' -UseBasicParsing).Content
build_script:
  - ps: .\build.ps1
after_build:
  - cmd: xmake clean -P winpty
  - ps: cd ..
  - ps: Move-Item ts-xmake-gui ts-xmake-gui-bk
  - ps: New-Item ts-xmake-gui -Type directory
  - ps: Move-Item ts-xmake-gui-bk ts-xmake-gui\ts-xmake-gui
  - ps: cd ts-xmake-gui
artifacts:
  - path: ts-xmake-gui
    name: ts-xmake-gui-newnt
deploy:
  - provider: GitHub
    artifact: ts-xmake-gui-newnt
    draft: true
    description: 'temp'
    on:
      appveyor_repo_tag: true
    auth_token:
      secure: i6fhYJ/A8hJC3+zb+jwRNljh5pGKxhC03D5Gla6EowVBLaFolxA8X3ZeXE0aE0pZ
